### PR TITLE
Adding instructions for installing dependencies in anaconda

### PR DESCRIPTION
**Pull request by vinesmsuic**
Should work across all systems.

### CODE REVIEW

**Comment by antoinelame** [comment]
Not an expert of conda, but can't we do `conda install --file requirements.txt` ?

**Comment by vinesmsuic** [comment]
Not sure if this will work, but I know we do `conda env create -f environment.yml` to create the environment from a `environment.yml` file.

> Not an expert of conda, but can't we do `conda install --file requirements.txt` ?

**Comment by antoinelame** [comment]
Got it, could you provide an `environment.yml` then, with versions for each library, to avoid future breaking changes?

**Comment by antoinelame** [comment]
Thanks for your contribution @vinesmsuic

**Pull request merged**
